### ISSUE TITLE
Integration Broken in 2025.1

### ISSUE THREAD

**Issue by kmycek** [upsert/lutron-caseta-pro#85]
As of 2025.1, I am getting some failures in my log. More than likely related to #84 back in May, as it references "SUPPORT_CLOSE" and "SUPPORT_SET_SPEED". Is this integration still being maintained? I hope so. 

The errors that I am getting are: 
```
Logger: homeassistant.setup
Source: setup.py:497
First occurred: 1:20:54 PM (2 occurrences)
Last logged: 1:20:54 PM

Unable to prepare setup for platform 'lutron_caseta_pro.cover': Platform not found (cannot import name 'SUPPORT_CLOSE' from 'homeassistant.components.cover' (/usr/src/homeassistant/homeassistant/components/cover/__init__.py)).
Unable to prepare setup for platform 'lutron_caseta_pro.fan': Platform not found (cannot import name 'SUPPORT_SET_SPEED' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).
```

**Comment by ThirteenTX** [comment]
This integration has been the cornerstone of my home automation journey. I'm sad to see it go but all the features from the custom integration are in the core app now, from what I understand. I'll be migrating to that, tomorrow. The last closed fix was in March, and they closed it due to the lack of need. https://github.com/upsert/lutron-caseta-pro/issues/83#issuecomment-1974785579

**Comment by upsert** [comment]
I was not sure that anyone was still using this custom integration. I will try to get it updated and running under Home Assistant 2025.1.

**Comment by nclpl** [comment]
I am definitely still using it! It’s critical to my home. Thanks for your work on it over the years. 

All of my fans and switches seem to work in 2025.1. It’s the light entities that appear to be broken.

**Comment by upsert** [comment]
New updates have been pushed! I tried to test everything as best I could and it appears to be working without any warnings in 2025.1.1.

Also fixes #84.

**Comment by alexrusso51** [comment]
I am also still using this integration. Thank you so much for maintaining it!

As others mentioned the light entities broke with 25.1 but the way the custom integration and official one approach lights entities (switches and dimmers) is identical so I just migrated those to the official integration (took some doing with my 30+ lights appearing in multiple dashboards and custom template entries).

 It's the approach to Pico Remotes (sensors vs events) that I still much prefer using this integration over the original one for. Thankfully, that still works as it always has.

**Comment by frozenmartini** [comment]
Thank you so much for the update. The main Caseta integration doesn’t support Triathlon Wood Blind, but yours does. It’s been one of my most used integrations, and I was disappointed because I thought since the last update was three years ago, it probably wouldn’t be fixed. Thank you again for taking your time to patch it.
